### ISSUE TITLE
Module not found: Can't resolve 'react-json-to-table'

### ISSUE THREAD

**Issue by kubil-ismail** [thehyve/react-json-to-table#15]
Hi i have problem, here my problem Module not found: Can't resolve 'react-json-to-table', i was deleted my node_modules & package-lock.json but still error.

**Comment by atul767464** [comment]
same  error dont know why

**Comment by atul767464** [comment]
i fixed the issue by using  older version 
use this version "react-json-to-table": "0.1.1"

**Comment by pvannierop** [comment]
@kubil-ismail @atul767464 I have created a patched version 0.1.7. Could you let me know whether this works for you?

**Comment by pvannierop** [comment]
This issue has been resolved with release v0.1.7. Closing issue.

**Comment by atul767464** [comment]
> @kubil-ismail @atul767464 I have created a patched version 0.1.7. Could you let me know whether this works for you?

Sorry that project got delivered so , I didn't tested on newer version

**Comment by pvannierop** [comment]
@atul767464 No worries! Thank you for your feedback.
