### ISSUE TITLE
Module not found: Can't resolve 'react-json-to-table'

### ISSUE THREAD

**Issue by suhasholla3** [thehyve/react-json-to-table#16]
I am unable to use this package as there is a "Failed to compile" error.

**Comment by NilsoJunior** [comment]
I have the same problem mentioned above "Failed to compile"

**Comment by GiacintoCarlucci** [comment]
The latest version (**0.1.6** right now) seems to not have the build folder once installed.

You can check in **/node_modules/react-json-to-table/**:

![immagine](https://user-images.githubusercontent.com/37305243/95087157-a0525e80-0721-11eb-8c94-1531c84249b4.png)

If the build folder is missing do the following:

- remove the package: `npm remove react-json-to-table`
- install the previous working version: `npm install --save react-json-to-table@0.1.5`

After the installation process you should have the build folder under  **/node_modules/react-json-to-table/** and everything should work correctly.

Happy coding! ✌️

**Comment by pvannierop** [comment]
@GiacintoCarlucci @NilsoJunior @suhasholla3 I have created a patched version __0.1.7__. Could you let me know whether this works for you?

**Comment by GiacintoCarlucci** [comment]
Yes, I just checked and it works properly 👍
By the way... what are the differences between 0.1.7 and 0.1.5?

**Comment by suhasholla3** [comment]
@pvannierop Hey it works. Thanks 🎉

**Comment by NilsoJunior** [comment]
Sorry! Yes, I just checked and it works properly
