### ISSUE TITLE
Table doesnt work for json with boolean values

### ISSUE THREAD

**Issue by JaLe29** [thehyve/react-json-to-table#3]
When my JSON object contains boolean value, the field in table is empty.

excepted longMode: false

![image](https://user-images.githubusercontent.com/22296816/48979009-f3cedc80-f0b4-11e8-911e-a9c6f3461869.png)

**Comment by johngrandson** [comment]
Try to render the value in string, like 'false'.

**Comment by KamilError** [comment]
you wont be able to print out values like that, what you should do:
longMode ? 'true' : 'false';

**Comment by JaLe29** [comment]
@KamilError Sure, like in title `with boolean values`, `"true"` is string, but yes, this is working solution.

**Comment by pvannierop** [comment]
Fixed in PR #18
